FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=neon/neon
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY neon.tar.gz /neon.tar.gz
RUN tar -xvf /neon.tar.gz

#ADD . /neon
RUN cd /neon/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /neon && scripts/windows-crosscompile/compile-neon.sh
