.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. neon_qt test_neon_qt
clean: FORCE
	$(MAKE) -C .. neon_qt_clean test_neon_qt_clean
check: FORCE
	$(MAKE) -C .. test_neon_qt_check
neon-qt neon-qt.exe: FORCE
	 $(MAKE) -C .. neon_qt
